//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspire_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Person_Course = new HashSet<Person_Course>();
        }
    
        public int Person_ID { get; set; }
        public string Person_Name { get; set; }
        public string Person_Surname { get; set; }
        public string Person_Email { get; set; }
        public string Person_Password { get; set; }
        public string Person_Type { get; set; }
        public string Person_Level { get; set; }
        public string Person_School { get; set; }
        public string DocFile { get; set; }
        public Nullable<int> Centre_ID { get; set; }
    
        public virtual Centre Centre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Course> Person_Course { get; set; }
        public virtual PersonSubject PersonSubject { get; set; }
        public bool Is_Active { get; internal set; }
    }
}
