//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspire_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Course
    {
        public int Person_Course_ID { get; set; }
        public string Is_Active { get; set; }
        public System.DateTime Date_Reg { get; set; }
        public System.DateTime Date_Dereg { get; set; }
        public string Dereg_Reason { get; set; }
        public Nullable<System.DateTime> Years { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}
